# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [ ]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

In [ ]:
if numbers_x[0] == numbers_x[-1]:
  print(True)
else:
  print(False)

True


In [ ]:
if numbers_y[0] == numbers_y[-1]:
  print(True)
else:
  print(False)

False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [ ]:
import numpy as np

In [ ]:
#code here
nparray1=np.array([1,2,3,4,5])
nparray2=np.array([6,7,8,9,10])
# element-wise addition
nparray3=nparray1+nparray2
nparray3

array([ 7,  9, 11, 13, 15])

In [ ]:
#element-wise multiplication
nparray4=nparray1*nparray2
nparray4

array([ 6, 14, 24, 36, 50])

# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
#code here
array1d=np.arange(1,24,2)
array1d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
array2d=array1d.reshape(3,4)
array2d

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
arr1=np.arange(1,20,2)
arr1=arr1.reshape(2,5)
arr1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
arr2=np.array([[2,3,4,5,6],
               [1,2,3,4,5]])
arr2

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [ ]:
#vertical concatenation
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [ 2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [ 2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5]])

In [ ]:
#horizontal concatenation
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  5,  7,  9,  2,  3,  4,  5,  6],
       [11, 13, 15, 17, 19,  1,  2,  3,  4,  5]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5,  7,  9,  2,  3,  4,  5,  6],
       [11, 13, 15, 17, 19,  1,  2,  3,  4,  5]])

# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [ ]:
#Code here
shop={1:"Fruits",2:"Vegetables",3:"Meat"}
shopping_cart=[]
quitkey='q'
keypress='s'
confirm='y'
print("Welcome to SuperMarket")
#print("Available Products:\nPress 1 to Add to your cart: Fruits.\nPress 2 to Add to your cart: Vegetables.\nPress 3 to Add to your cart: Meat\nPress q to Quit")
while keypress != quitkey:
  keypress=input("Available Products:\nPress 1 to Add to your cart: Fruits.\nPress 2 to Add to your cart: Vegetables.\nPress 3 to Add to your cart: Meat\nPress q to Quit\n")
  if keypress=='1':
    confirm=input("Are you sure you want to add Fruits.\nPress y to confirm and any other key to cancel.")
    if confirm == 'y':
      shopping_cart.append('Fruits')
  elif keypress=='2':
    confirm=input("Are you sure you want to add Vegetables.\nPress y to confirm and any other key to cancel.")
    if confirm == 'y':
      shopping_cart.append('Vegetables')
  elif keypress=='3':
    confirm=input("Are you sure you want to add Meat.\nPress y to confirm and any other key to cancel.")
    if confirm == 'y':
      shopping_cart.append('Meats')
print("Your Cart: ",shopping_cart)
print("Thanks for shopping.")

Welcome to SuperMarket
Available Products:
Press 1 to Add to your cart: Fruits.
Press 2 to Add to your cart: Vegetables.
Press 3 to Add to your cart: Meat
Press q to Quit
1
Are you sure you want to add Fruits.
Press y to confirm and any other key to cancel.y
Available Products:
Press 1 to Add to your cart: Fruits.
Press 2 to Add to your cart: Vegetables.
Press 3 to Add to your cart: Meat
Press q to Quit
q
Your Cart:  ['Fruits']
Thanks for shopping.


In [ ]:
shop={1:"Fruits",2:"Vegetables",3:"Meat"}
shop[1]

'Fruits'

# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [ ]:
#code here
imp=['important','urgent','inform','importance','necessary']
important=[]
spam=['Free money','Click below','Click here','100% free','100% satisfied']
spammail=[]
promo=['Limited Time Offer','Exclusive Deal','Exclusive Offer','Introducing']
promotional=[]
emails=["Dear sir, it is important to note that i do my work on time. Thanks.","We are offering you 100% free free money get yours by clicking link below","Dear Customer, We have brought you an Exclusive Deal.Thanks."]
for i in emails:
  if any(x in i for x in imp):
    important.append(i)
  elif any(x in i for x in spam):
    spammail.append(i)
  elif any(x in i for x in promo):
    promotional.append(i)
print("IMPORTANT", important)
print("SPAM", spammail)
print("Promotions", promotional)

IMPORTANT ['Dear sir, it is important to note that i do my work on time. Thanks.']
SPAM ['We are offering you 100% free free money get yours by clicking link below']
Promotions ['Dear Customer, We have brought you an Exclusive Deal.Thanks.']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [ ]:
#code here
engtospan={"hi":"hola","bye":"adiós","red":"rojo","blue":"azul","how":"cómo","you":"tú","i am":"soy","why":"por qué"}
keyp='s'
while keyp != 'q':
  word=input("Enter English word\n")
  if word in engtospan.keys():
    print(word," : ",engtospan.get(word))
  else:
    print("the translation is not available")
  keyp=input("would you like to quit Press q. If you would like to trranslate again press any key.\n")


Enter English word
red
red  :  rojo
would you like to quit Press q. If you would like to trranslate again press any key.
q


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [ ]:
import pandas as pd

url="https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df=pd.read_csv(url)
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [ ]:
totalglobal=df['Global_Sales'].sum()
totalglobal

8920.44

In [ ]:
game=df['Global_Sales'].max()
game

82.74

In [ ]:
print(df[df.Global_Sales==game])

   Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74  


In [ ]:
#(NA_Sales, EU_Sales, JP_Sales, Other_Sales)
navg=df['NA_Sales'].mean()
euavg=df['EU_Sales'].mean()
other=df['Other_Sales'].mean()
print("NA_Sales Average",navg)
print("EU_Sales Average",euavg)
print("Other_Sales Average",other)

NA_Sales Average 0.26466742981082064
EU_Sales Average 0.14665200626581515
Other_Sales Average 0.0480630196409206


In [ ]:
#Find the top 5 most popular game genres based on global sales.
topglobalgenre=df.groupby('Genre')['Global_Sales'].sum()
top5=topglobalgenre.nlargest(5)
top5

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [ ]:
#Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
df.groupby('Genre')[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum()

NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [ ]:
NAgenre=df.groupby('Genre')['NA_Sales'].sum().nlargest(1)
NAgenre

Genre
Action    877.83
Name: NA_Sales, dtype: float64

In [ ]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [ ]:
#Determine the top 3 gaming platforms with the highest global sales.
gaming=df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
gaming

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [ ]:
# Calculate the market share (percentage of global sales) for each genre.
#groupby genre with global sales / global sales both already done above
topglobalgenre=df.groupby('Genre')['Global_Sales'].sum()
totalglobal=df['Global_Sales'].sum()
market=(topglobalgenre/totalglobal)*100
market


Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [ ]:
#Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [ ]:
df['NA_Sales'].corr(df['EU_Sales'])

0.7677267483702631